/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CounTo: typeof import('./src/components/CounTo/index.vue')['default']
    Echarts: typeof import('./src/components/Echarts/index.vue')['default']
    FormDrawer: typeof import('./src/components/FormDrawer/index.vue')['default']
    InfoButton: typeof import('./src/components/InfoButton/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search/index.vue')['default']
    SearchItem: typeof import('./src/components/SearchItem/index.vue')['default']
    UploadFile: typeof import('./src/components/UploadFile/index.vue')['default']
    UploadImg: typeof import('./src/components/UploadImg/index.vue')['default']
  }
}
